// Generated by gencpp from file planner_and_control/Gngga.msg
// DO NOT EDIT!


#ifndef PLANNER_AND_CONTROL_MESSAGE_GNGGA_H
#define PLANNER_AND_CONTROL_MESSAGE_GNGGA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner_and_control
{
template <class ContainerAllocator>
struct Gngga_
{
  typedef Gngga_<ContainerAllocator> Type;

  Gngga_()
    : latitude(0.0)
    , longitude(0.0)
    , quality_indicator()  {
    }
  Gngga_(const ContainerAllocator& _alloc)
    : latitude(0.0)
    , longitude(0.0)
    , quality_indicator(_alloc)  {
  (void)_alloc;
    }



   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _quality_indicator_type;
  _quality_indicator_type quality_indicator;





  typedef boost::shared_ptr< ::planner_and_control::Gngga_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_and_control::Gngga_<ContainerAllocator> const> ConstPtr;

}; // struct Gngga_

typedef ::planner_and_control::Gngga_<std::allocator<void> > Gngga;

typedef boost::shared_ptr< ::planner_and_control::Gngga > GnggaPtr;
typedef boost::shared_ptr< ::planner_and_control::Gngga const> GnggaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_and_control::Gngga_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_and_control::Gngga_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_and_control::Gngga_<ContainerAllocator1> & lhs, const ::planner_and_control::Gngga_<ContainerAllocator2> & rhs)
{
  return lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.quality_indicator == rhs.quality_indicator;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_and_control::Gngga_<ContainerAllocator1> & lhs, const ::planner_and_control::Gngga_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_and_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner_and_control::Gngga_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_and_control::Gngga_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_and_control::Gngga_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_and_control::Gngga_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_and_control::Gngga_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_and_control::Gngga_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_and_control::Gngga_<ContainerAllocator> >
{
  static const char* value()
  {
    return "887c2979d6bd1163174852792c69db98";
  }

  static const char* value(const ::planner_and_control::Gngga_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x887c2979d6bd1163ULL;
  static const uint64_t static_value2 = 0x174852792c69db98ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_and_control::Gngga_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_and_control/Gngga";
  }

  static const char* value(const ::planner_and_control::Gngga_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_and_control::Gngga_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 latitude\n"
"float64 longitude\n"
"string quality_indicator # 0 - fix not available, 1 - GPS fix, 2 - Differential GPS fix\n"
"\n"
;
  }

  static const char* value(const ::planner_and_control::Gngga_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_and_control::Gngga_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.quality_indicator);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gngga_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_and_control::Gngga_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_and_control::Gngga_<ContainerAllocator>& v)
  {
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "quality_indicator: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.quality_indicator);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_AND_CONTROL_MESSAGE_GNGGA_H
