// Generated by gencpp from file planner_and_control/Obstacles.msg
// DO NOT EDIT!


#ifndef PLANNER_AND_CONTROL_MESSAGE_OBSTACLES_H
#define PLANNER_AND_CONTROL_MESSAGE_OBSTACLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <planner_and_control/SegmentObstacle.h>
#include <planner_and_control/CircleObstacle.h>

namespace planner_and_control
{
template <class ContainerAllocator>
struct Obstacles_
{
  typedef Obstacles_<ContainerAllocator> Type;

  Obstacles_()
    : header()
    , segments()
    , circles()  {
    }
  Obstacles_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , segments(_alloc)
    , circles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::planner_and_control::SegmentObstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::planner_and_control::SegmentObstacle_<ContainerAllocator> >::other >  _segments_type;
  _segments_type segments;

   typedef std::vector< ::planner_and_control::CircleObstacle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::planner_and_control::CircleObstacle_<ContainerAllocator> >::other >  _circles_type;
  _circles_type circles;





  typedef boost::shared_ptr< ::planner_and_control::Obstacles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_and_control::Obstacles_<ContainerAllocator> const> ConstPtr;

}; // struct Obstacles_

typedef ::planner_and_control::Obstacles_<std::allocator<void> > Obstacles;

typedef boost::shared_ptr< ::planner_and_control::Obstacles > ObstaclesPtr;
typedef boost::shared_ptr< ::planner_and_control::Obstacles const> ObstaclesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_and_control::Obstacles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_and_control::Obstacles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_and_control::Obstacles_<ContainerAllocator1> & lhs, const ::planner_and_control::Obstacles_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.segments == rhs.segments &&
    lhs.circles == rhs.circles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_and_control::Obstacles_<ContainerAllocator1> & lhs, const ::planner_and_control::Obstacles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_and_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner_and_control::Obstacles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_and_control::Obstacles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_and_control::Obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_and_control::Obstacles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_and_control::Obstacles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_and_control::Obstacles_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_and_control::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d1ad5dcfab44f5899cb5e192beb9c8f9";
  }

  static const char* value(const ::planner_and_control::Obstacles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd1ad5dcfab44f589ULL;
  static const uint64_t static_value2 = 0x9cb5e192beb9c8f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_and_control::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_and_control/Obstacles";
  }

  static const char* value(const ::planner_and_control::Obstacles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_and_control::Obstacles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"planner_and_control/SegmentObstacle[] segments\n"
"planner_and_control/CircleObstacle[] circles\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: planner_and_control/SegmentObstacle\n"
"geometry_msgs/Point first_point\n"
"geometry_msgs/Point last_point\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: planner_and_control/CircleObstacle\n"
"geometry_msgs/Point center\n"
"float64 radius\n"
"\n"
;
  }

  static const char* value(const ::planner_and_control::Obstacles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_and_control::Obstacles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.segments);
      stream.next(m.circles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obstacles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_and_control::Obstacles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_and_control::Obstacles_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "segments[]" << std::endl;
    for (size_t i = 0; i < v.segments.size(); ++i)
    {
      s << indent << "  segments[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::planner_and_control::SegmentObstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.segments[i]);
    }
    s << indent << "circles[]" << std::endl;
    for (size_t i = 0; i < v.circles.size(); ++i)
    {
      s << indent << "  circles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::planner_and_control::CircleObstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.circles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_AND_CONTROL_MESSAGE_OBSTACLES_H
