// Generated by gencpp from file planner_and_control/Sign.msg
// DO NOT EDIT!


#ifndef PLANNER_AND_CONTROL_MESSAGE_SIGN_H
#define PLANNER_AND_CONTROL_MESSAGE_SIGN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner_and_control
{
template <class ContainerAllocator>
struct Sign_
{
  typedef Sign_<ContainerAllocator> Type;

  Sign_()
    : name()
    , x()
    , y()  {
    }
  Sign_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , x(_alloc)
    , y(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _x_type;
  _x_type x;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::planner_and_control::Sign_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_and_control::Sign_<ContainerAllocator> const> ConstPtr;

}; // struct Sign_

typedef ::planner_and_control::Sign_<std::allocator<void> > Sign;

typedef boost::shared_ptr< ::planner_and_control::Sign > SignPtr;
typedef boost::shared_ptr< ::planner_and_control::Sign const> SignConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_and_control::Sign_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_and_control::Sign_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner_and_control::Sign_<ContainerAllocator1> & lhs, const ::planner_and_control::Sign_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner_and_control::Sign_<ContainerAllocator1> & lhs, const ::planner_and_control::Sign_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner_and_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner_and_control::Sign_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_and_control::Sign_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_and_control::Sign_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_and_control::Sign_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_and_control::Sign_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_and_control::Sign_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_and_control::Sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb16051b6837ac6b55cf033d3dd585e0";
  }

  static const char* value(const ::planner_and_control::Sign_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb16051b6837ac6bULL;
  static const uint64_t static_value2 = 0x55cf033d3dd585e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_and_control::Sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_and_control/Sign";
  }

  static const char* value(const ::planner_and_control::Sign_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_and_control::Sign_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float64[] x\n"
"float64[] y\n"
;
  }

  static const char* value(const ::planner_and_control::Sign_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_and_control::Sign_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sign_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_and_control::Sign_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_and_control::Sign_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_AND_CONTROL_MESSAGE_SIGN_H
