(cl:in-package planner_and_control-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          HEADING-VAL
          HEADING
          INDEX-VAL
          INDEX
          TARGET_SPEED-VAL
          TARGET_SPEED
          TARGET_BRAKE-VAL
          TARGET_BRAKE
          TARGET_GEAR-VAL
          TARGET_GEAR
          SPEED-VAL
          SPEED
          STEER-VAL
          STEER
          BRAKE-VAL
          BRAKE
          GEAR-VAL
          GEAR
          AUTO_MANUAL-VAL
          AUTO_MANUAL
          MAP_FOLDER-VAL
          MAP_FOLDER
          MAP_FILE-VAL
          MAP_FILE
))